// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/starred": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/starred" | "/chat" | "/settings" | "/login" | "/sign-up";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/starred.tsx": {
    id: "routes/starred";
    page: "/starred";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/starred": typeof import("./app/routes/starred.tsx");
  "routes/chat": typeof import("./app/routes/chat.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/sign-up": typeof import("./app/routes/sign-up.tsx");
};