// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/styles": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/styles";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/styles.tsx": {
    id: "routes/styles";
    page: "/styles";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/styles": typeof import("./app/routes/styles.tsx");
};